#!/bin/bash

# set the number of nodes and processes per node
#PBS -l nodes=1:ppn=8

# set max wallclock time, here itis set to 72h
#PBS -l walltime=72:00:00

# set name of job
#PBS -N jrod_job



./run