#!/bin/bash

Nmax=10 ##qubit ensemble dimension must be even
nmax=20 ##field dimension only even numbers 
Delta=1.0
eta=0.2
gamma=0.3
omega=1.0
omega0=1.0
en=0.8


python plot.py 50 100 1.0 1.0 1.0 0.2 0.3 0.5

echo "one done"

python plot.py 50 100 1.0 1.0 1.0 0.2 0.8 0.5

echo "two done"

python plot.py 50 100 1.0 1.0 1.0 2.1 0.8 0.5