#!/bin/bash

Nmax=200 ##qubit ensemble dimension must be even
nmax=600 ##field dimension only even numbers 
Delta=1.0
eta=0.2
gamma=0.3
omega=1.0
omega0=1.0
en=0.05


python plot.py $Nmax $nmax 1.0 1.0 1.0 0.2 0.3 $en

echo "one done"

python plot.py $Nmax $nmax 1.0 1.0 1.0 0.2 0.8 $en

echo "two done"

python plot.py $Nmax $nmax 1.0 1.0 1.0 2.1 0.8 $en