#!/bin/bash
#
#SBATCH --job-name=test
#SBATCH --output=plot.txt
#
#SBATCH --ntasks=8

Nmax=200 ##qubit ensemble dimension must be even
nmax=600 ##field dimension only even numbers 
en=0.1

cd /home/fishy/code/Mexico/Dicke-lmg/dicky-lmg/
python plot.py $Nmax $nmax 1.0 1.0 1.0 0.2 0.3 $en

echo "one done"

python plot.py $Nmax $nmax 1.0 1.0 1.0 0.2 0.8 $en

echo "two done"

python plot.py $Nmax $nmax 1.0 1.0 1.0 2.1 0.6 $en
